encrypt-type: # 0：普通， 1：国密
 encrypt-type: 0

group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  # 群组ID
    connections-str:
                    - 13.75.70.153:20200  # 节点，listen_ip:channel_listen_port
                    - 13.75.70.153:20201
                    - 13.75.70.153:20202
                    - 13.75.70.153:20203

channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: fisco # 机构名称

server:
  port: 9999